version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '6600:3306'
    volumes:
      - mysqlDB:/var/lib/mysql
    env_file:
      - ./auth/env.docker
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: passw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: passw0rd
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
  golang_app:
    build: ./auth
    container_name: golang_app
    env_file:
      - ./auth/env.docker
    ports:
      - '8000:8000'
    volumes:
      - ./auth/src:/app
      - /app/go.mod
      - /app/go.sum
    depends_on:
      - redis
      - mysql
    restart: on-failure
volumes:
  redisDB:
  mysqlDB: